version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      semver-patch-days: 7
    allow:
      - dependency-type: "all"
    open-pull-requests-limit: 5
    labels:
      - "waiting"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: scope
    groups:
      patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: "weekly"
      day: "monday"
    cooldown:
      semver-patch-days: 7
    open-pull-requests-limit: 5
    groups:
      all-actions:
        patterns:
          - "*"
