version: 2
updates:
  # Production dependencies - daily updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      semver-patch-days: 7
    allow:
      - dependency-type: "production"
    open-pull-requests-limit: 5
    labels:
      - "waiting"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: scope
  # Development dependencies - monthly updates
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'monday'
    cooldown:
      semver-patch-days: 7
    allow:
      - dependency-type: "development"
    open-pull-requests-limit: 5
    labels:
      - "waiting"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: scope
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: "monthly"
      day: "monday"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 5
    groups:
      all-actions:
        patterns:
          - "*"
