---
extends:
  - "@commitlint/config-conventional"
rules:
  body-max-line-length: [2, "always", 80]
  # Need to allow other cases for the subject.
  # See https://github.com/dependabot/dependabot-core/issues/11705
  subject-case: [0]
