---
pull_request_rules:
  - name: automatic merge
    conditions:
      - and: &base_checks
        - base=main
        - -label~=^acceptance-tests-needed|not-ready
        - '-check-failure ~= ^(?!(Rule:|Mergify|Summary))'
        - '-check-pending ~= ^(?!(Rule:|Mergify|Summary))'
        - check-success=only-test
        - check-success=checkstyle-perl
        - check-success=checkstyle-npm
        - linear-history
      - and:
        - "#approved-reviews-by>=2"
        - "#changes-requested-reviews-by=0"
        # https://doc.mergify.io/examples.html#require-all-requested-reviews-to-be-approved
        - "#review-requested=0"
    actions: &merge
      merge:
        method: fast-forward
  - name: automatic merge on special label
    conditions:
      - and: *base_checks
      - and:
        # mergify config checks needs at least two rules in "and" so we repeat
        # one from the base checks
        - base=main
        - "label=merge-fast"
    actions: *merge
  - name: automatic merge for dependabot updates
    conditions:
      - and: *base_checks
      - and:
        # mergify config checks needs at least two rules in "and" so we repeat
        # one from the base checks
        - base=main
        - author=dependabot[bot]
    actions: *merge
  # dependabot only rebases on conflicts, not when merely behind main
  - name: rebase green dependabot updates behind main
    conditions:
      - and: *base_checks
      - and:
        - author=dependabot[bot]
        - "#commits-behind>0"
    actions: &rebase
      rebase:
        bot_account: suse-qe-tools-mergify
  - name: continuously rebase pull requests when it's labeled with `rebase`
    conditions:
      - label=rebase
    actions: *rebase
