requires 'Mojolicious', '>= 9.39';
requires 'Mojolicious::Plugin::OpenAPI';
requires 'Mojo::Pg', '>= 4.25';
requires 'CPAN::Audit';
requires 'Cpanel::JSON::XS', '>= 4.40';
requires 'Devel::Cover';
requires 'JSON::Validator';
requires 'IO::Socket::SSL', '>= 2.009';
requires 'Test::Harness', '>= 3.48';
requires 'Test::Output';
requires 'Test::Warnings';
