---
name: checkstyle (NPM)
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  checkstyle-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v6
      with:
        fetch-depth: 0
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
      with:
        node-version: '22'
    - name: Install JS dependencies
      run: make install-deps-js
    - name: Install gitlint
      run: pip install gitlint
    - name: Run checkstyle
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          make checkstyle-npm COMMIT_ARGS="--commits origin/${{ github.base_ref }}..HEAD --verbose"
        else
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.event.after }}"
          if [ "$BEFORE" == "0000000000000000000000000000000000000000" ] || ! git cat-file -e "$BEFORE" >/dev/null 2>&1; then
            make checkstyle-npm COMMIT_ARGS="--verbose"
          else
            make checkstyle-npm COMMIT_ARGS="--commits $BEFORE..$AFTER --verbose"
          fi
        fi
