---
name: checkstyle (NPM)
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  checkstyle-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      with:
        fetch-depth: 0
    - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e  # v6.4.0
      with:
        node-version: '22'
    - name: Install JS dependencies
      run: make install-deps-js
    - name: Install gitlint
      run: pip install gitlint
    - name: Run checkstyle
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          make checkstyle-npm COMMIT_ARGS="--commits ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --verbose"
        else
          make checkstyle-npm COMMIT_ARGS="--commits HEAD --verbose"
        fi
