name: test
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  only-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v6
      - uses: shogo82148/actions-setup-perl@8a3e458e34220c3cd62497d8c297eae315b88a72  # v1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '22'
      - name: node -v
        run: node -v
      - name: Install JS dependencies
        run: make install-deps-js
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          make install-deps-ubuntu install-deps-cpanm
      - name: Run all tests with coverage
        run: make only-test-coverage
      - name: Check assets
        run: ls public/asset
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cover -report Coveralls
